config/routes.rb
Rails.application.routes.draw do
  root 'heros#index'
  resources :heros
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  http_basic_authenticate_with name: Rails.application.credentials.authenticate[:name], 
                           password: Rails.application.credentials.authenticate[:password], 
                           except: %i[index show]
  before_action :set_hero, only: %i[ show edit update destroy ]

  # GET /heros or /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1 or /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros or /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: "Hero was successfully created." }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1 or /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: "Hero was successfully updated." }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1 or /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: "Hero was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hero_params
      params.require(:hero).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/heros/_form.html.erb
<%= form_with(model: hero) do |form| %>
  <% if hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
        <% hero.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/heros/edit.html.erb
<h1>Editing Hero</h1>

<%= render 'form', hero: @hero %>

<%= link_to 'Show', @hero %> |
<%= link_to 'Back', heros_path %>

app/views/heros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Heroes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.name %></td>
        <td><%= link_to 'Show', hero %></td>
        <td><%= link_to 'Edit', edit_hero_path(hero) %></td>
        <td><%= link_to 'Destroy', hero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hero', new_hero_path %>

app/views/heros/new.html.erb
<h1>New Hero</h1>

<%= render 'form', hero: @hero %>

<%= link_to 'Back', heros_path %>

app/views/heros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hero.name %>
</p>

<%= link_to 'Edit', edit_hero_path(@hero) %> |
<%= link_to 'Back', heros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CursoRails6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>